name: Deploy

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
      WOWI_API_TOKEN:
        required: true
      WAGO_API_TOKEN:
        required: true

jobs:
  changelog:
    uses: ./.github/workflows/changelog.yml@main
  deploy:
    needs: changelog
    runs-on: ubuntu-latest
    steps:
      - name: Package and release
        uses: BigWigsMods/packager@v2
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
