name: Deploy

on: workflow_call

jobs:
  changelog:
    uses: .github/workflows/changelog.yml
  deploy:
    needs: changelog
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: BigWigsMods/packager@v2
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
