name: Package and release

on: [push, pull_request]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  deploy:
    needs: lint
    uses: ./.github/workflows/deploy.yml
  status:
    needs: [lint, deploy]
    if: ${{ failure() }}
    uses: ./.github/workflows/status.yml
    with:
      status: ${{ job.status }}
