name: Package and release

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  lint_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Code
        uses: nebularg/actions-luacheck@v1
        with:
          args: --no-color
          annotate: warning

  package_and_release:
    needs: lint_code
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Changelog
        run: ./.github/scripts/generate_changelog.sh
        shell: bash

      - name: Package and Release
        uses: BigWigsMods/packager@v2
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}

  notify_failures:
    needs: [lint_code, package_and_release]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Status to Discord
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          status: failure
