name: Status

on:
  workflow_call:
    secrets:
      WEBHOOK_URL:
        required: true
    inputs:
      status:
        type: string
        required: true

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          status: ${{ inputs.status }}
